name: 'Terraform Plan + PR add comment'

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      TF_VERSION: 1.5.7
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      tf_actions_working_dir: .
      TF_IN_AUTOMATION: true
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: init
      run: terraform -chdir=soluciones/dnazareno-workload init

    - name: Terraform Plan
      id: plan
      run: terraform -chdir=soluciones/dnazareno-workload plan -no-color
      continue-on-error: true

    - name: Post Plan
      #if: always() && github.ref != 'refs/heads/master' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
      uses: robburger/terraform-pr-commenter@v1
      with:
        commenter_type: plan
        commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
