name: 'Terraform Plan'

on:
  workflow_dispatch:
#  push:
#    branches:
#    - main
#  pull_request:
#    branches:
#    - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

#    - name: Azure Logout
#      run: az logout
            
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform -chdir=soluciones/dnazareno-workload init

    - name: Terraform Plan
      run: terraform terraform -chdir=soluciones/dnazareno-workload plan
