name: 'Terraform Plan'

on:
  workflow_dispatch:
#  push:
#    branches:
#    - main
#  pull_request:
#    branches:
#    - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    #- uses: azure/login@v2
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}
    #    enable-AzPSSession: true
    - name: Azure Login
      run: |
        #az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
         export ARM_CLIENT_ID=${{ secrets.CLIENT_ID }}
         export ARM_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
         export ARM_SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}
         export ARM_TENANT_ID=${{ secrets.TENANT_ID }}
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform -chdir=soluciones/dnazareno-workload init

    - name: Terraform Plan
      run: terraform terraform -chdir=soluciones/dnazareno-workload plan
